-- Phase 2 schema additions for TrackMyGig (run in Supabase SQL editor)

-- Wishlist table (separate from favorites)
create table if not exists public.wishlists (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users (id) on delete cascade,
  concert_id bigint not null references public.concerts (id) on delete cascade,
  created_at timestamptz default now() not null,
  unique (user_id, concert_id)
);

-- Extend concerts with ticketing + venue detail fields
alter table public.concerts
  add column if not exists min_price numeric,
  add column if not exists max_price numeric,
  add column if not exists ticket_status text,
  add column if not exists venue_address text,
  add column if not exists latitude numeric,
  add column if not exists longitude numeric;

-- Recommended notification types (no schema change; guidance only):
-- UPCOMING_SHOW_REMINDER, PRICE_DROP, LOW_TICKETS, GENERAL
